### ISSUE TITLE
Error during PyYAML-5.4.1 install

### ISSUE THREAD

**Issue by Ivarz** [GenomicDataInfrastructure/starter-kit-beacon2-ri-api#3]
Hi! I have encountered an issue when trying to deploy the starter kit. More specifically, it seems that `pip install` of PyYAML fails. Output from `docker-compose`:
```
Building beacon
Sending build context to Docker daemon  19.28MB
Step 1/22 : FROM python:3.10-buster AS BUILD
 ---> 31f7904d7bdb
Step 2/22 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 2a877aa1d1ab
Step 3/22 : RUN apt-get update
 ---> Using cache
 ---> 6c996a191784
Step 4/22 : RUN apt-get install -y --no-install-recommends     ca-certificates pkg-config make     libssl-dev libffi-dev libpq-dev
 ---> Using cache
 ---> 81bbc6b543ac
Step 5/22 : RUN pip install --upgrade pip
 ---> Using cache
 ---> 2f2e60eb1dd0
Step 6/22 : COPY requirements.txt /tmp/requirements.txt
 ---> Using cache
 ---> a88d52cd59e2
Step 7/22 : RUN pip install -r /tmp/requirements.txt
 ---> Running in f742c9b53a9a
Collecting aiohttp==3.8.1 (from -r /tmp/requirements.txt (line 5))
  Downloading aiohttp-3.8.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 2.1 MB/s eta 0:00:00
Collecting aiohttp-cors==0.7.0 (from -r /tmp/requirements.txt (line 6))
  Downloading aiohttp_cors-0.7.0-py3-none-any.whl (27 kB)
Collecting asyncpg~=0.24.0 (from -r /tmp/requirements.txt (line 7))
  Downloading asyncpg-0.24.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 3.7 MB/s eta 0:00:00
Collecting pyyaml~=5.4.1 (from -r /tmp/requirements.txt (line 8))
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 5.9 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      /tmp/pip-build-env-opy2fvg8/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-opy2fvg8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-opy2fvg8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-opy2fvg8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-opy2fvg8/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-opy2fvg8/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-opy2fvg8/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-opy2fvg8/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-opy2fvg8/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-opy2fvg8/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-opy2fvg8/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 319, in run
          self.find_sources()
        File "/tmp/pip-build-env-opy2fvg8/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 327, in find_sources
          mm.run()
        File "/tmp/pip-build-env-opy2fvg8/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 549, in run
          self.add_defaults()
        File "/tmp/pip-build-env-opy2fvg8/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 587, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-opy2fvg8/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-opy2fvg8/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-opy2fvg8/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-opy2fvg8/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
The command '/bin/sh -c pip install -r /tmp/requirements.txt' returned a non-zero code: 1
ERROR: Service 'beacon' failed to build : Build failed
```

Previously it worked without problems. It seems that there is an issue with PyYAML itself yaml/pyyaml#724.

OS: Debian 12
Docker version 20.10.24+dfsg1, build 297e129
docker-compose version 1.29.2
Python 3.11.2

**Comment by costero-e** [comment]
Thanks @Ivarz for opening the issue. As @lgadelha suggested in the PR i just merged, the solution is changing the pyyaml version to 6.0.1 as it seems that cython had an update last month and now pyyaml 5.4.1 version failed to work properly with the new version of cython.
